// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package currencyexchange

import (
	"os"
	"rate-exchange-api/internal/model"
)

// Injectors from wire.go:

func InitializeService() CurrencyExchangeService {
	exchangeRateMap := ProvideExchangeRateData()
	currencyExchangeService := NewCurrencyExchangeService(exchangeRateMap)
	return currencyExchangeService
}

// wire.go:

func ProvideExchangeRateData() model.ExchangeRateMap {
	filePath := os.Getenv("RATE_EXCHANGE_JSON_PATH")
	return LoadExchangeRateData(filePath)
}
